version: '3.8'

services:
  nginx:
    image: nginx
    container_name: petereport_nginx
    volumes:
      - ./nginx:/opt/petereport/nginx
      - ./nginx/petereport.conf:/etc/nginx/conf.d/petereport.conf
      - ./app/petereport/static:/opt/petereport/app/petereport/static
      - ./app/media:/opt/petereport/app/media
    ports:
      - 80:80
      - 443:443
    depends_on:
      - petereport

  petereport:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: petereport_django
    container_name: petereport_django
    environment:
      - PETEREPORT_DJANGO_DEBUG=False
      - PETEREPORT_DJANGO_AMIN_MODULE=True
      - PETEREPORT_MEDIA_HOST=https://localhost
      - PETEREPORT_MARTOR_UPLOAD_METHOD=MEDIA
      - PETEREPORT_PDF_ENGINE=xelatex
      - PETEREPORT_REPORT_TITLEPAGE_COLOR=b3e6ff
      - PETEREPORT_DJANGO_SENDFILE_BACKEND=django_sendfile.backends.nginx
    command: bash -c "
      sleep 1 &&
      pipenv install --deploy --ignore-pipfile --python 3.11 &&
      pip freeze &&
      pipenv run ./app/manage.py makemigrations &&
      pipenv run ./app/manage.py migrate &&
      pipenv run ./app/manage.py createfts &&
      pipenv run ./app/manage.py loaddata ./app/config/cwe-list.json &&
      pipenv run ./app/manage.py loaddata ./app/config/cwe-default.json &&
      pipenv run ./app/manage.py loaddata ./app/config/owasp-list.json &&
      pipenv run ./app/manage.py loaddata ./app/config/owasp-default.json &&
      pipenv run ./app/manage.py loaddata ./app/config/data-test.json &&
      pipenv run gunicorn --chdir ./app petereport.wsgi:application --timeout 120 --graceful-timeout 60 --bind 0.0.0.0:8000 --reload"
    volumes:
      - .:/opt/petereport
    expose:
      - 8000
    restart: unless-stopped