version: '3.8'

volumes:
  media:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app/media'
  sqlite_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app/db'
  storage_reports:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app/storage_reports'

services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx.complete
    image: petereport_nginx_complete
    container_name: petereport_nginx_complete
    volumes:
      - media:/opt/petereport/app/media:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - petereport

  petereport:
    build:
      context: .
      dockerfile: ./Dockerfile.petereport.complete
    image: petereport_django_complete
    container_name: petereport_django_complete
    environment:
      - PETEREPORT_DJANGO_DEBUG=False
      - PETEREPORT_DJANGO_AMIN_MODULE=False
    user: www-data
    command: bash -c "
      sleep 1 &&
      pipenv install --deploy --ignore-pipfile --python 3.9 &&
      pip freeze &&
      pipenv run ./app/manage.py makemigrations &&
      pipenv run ./app/manage.py migrate &&
      pipenv run ./app/manage.py createfts &&
      pipenv run ./app/manage.py loaddata ./app/config/cwe-list.json &&
      pipenv run ./app/manage.py loaddata ./app/config/cwe-default.json &&
      pipenv run ./app/manage.py loaddata ./app/config/owasp-list.json &&
      pipenv run ./app/manage.py loaddata ./app/config/owasp-default.json &&
      pipenv run gunicorn --chdir ./app petereport.wsgi:application --timeout 120 --graceful-timeout 60 --bind 0.0.0.0:8000"
    volumes:
      - sqlite_db:/opt/petereport/app/db:rw
      - media:/opt/petereport/app/media:rw
      - storage_reports:/opt/petereport/app/storage_reports:rw
    expose:
      - 8000
    restart: unless-stopped