version: '3.8'

volumes:
  media:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app/media'
  sqlite_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app/db'
  storage_reports:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './app/storage_reports'

services:
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx.complete
    image: petereport_nginx_complete
    container_name: petereport_nginx_complete
    volumes:
      - media:/opt/petereport/app/media:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - petereport

  petereport:
    build:
      context: .
      dockerfile: ./Dockerfile.petereport.complete
    image: petereport_django_complete
    container_name: petereport_django_complete
    environment:
      - PETEREPORT_DJANGO_DEBUG=False
      - PETEREPORT_DJANGO_AMIN_MODULE=False
      - PETEREPORT_MEDIA_HOST=https://localhost
      - PETEREPORT_MARTOR_UPLOAD_METHOD=MEDIA
      - PETEREPORT_REPORT_TITLEPAGE_COLOR=b3e6ff
      - PETEREPORT_DJANGO_SENDFILE_BACKEND=django_sendfile.backends.nginx
    user: www-data
    command: ./docker/run.sh
    volumes:
      - sqlite_db:/opt/petereport/app/db:rw
      - media:/opt/petereport/app/media:rw
      - storage_reports:/opt/petereport/app/storage_reports:rw
    expose:
      - 8000
    restart: unless-stopped