# Generated by Django 4.2 on 2023-05-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_deliverable',
            name='share_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_deliverable',
            name='share_uuid',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
