# Generated by Django 3.2.5 on 2021-09-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_appendix',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='db_finding_template',
            name='finding_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='db_finding_template',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='DB_AttackTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('attacktree', models.TextField(blank=True, null=True)),
                ('svg_file', models.TextField(blank=True, null=True)),
                ('finding', models.ManyToManyField(blank=True, related_name='attacktree_finding', to='preport.DB_Finding')),
            ],
        ),
    ]
