# Generated by Django 4.1.7 on 2023-04-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_report',
            name='audit_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='db_report',
            name='audit_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='db_report',
            name='report_date',
            field=models.DateField(),
        ),
    ]
