# Generated by Django 3.2.15 on 2022-09-19 06:58

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0002_auto_20210909_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_cwe',
            name='cwe_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_cwe',
            name='cwe_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='db_finding',
            name='description',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_finding',
            name='impact',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_finding',
            name='location',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_finding',
            name='recommendation',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_finding',
            name='references',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_finding_template',
            name='description',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_finding_template',
            name='impact',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_finding_template',
            name='location',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_finding_template',
            name='recommendation',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_finding_template',
            name='references',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_report',
            name='report_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='DB_Custom_field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', martor.models.MartorField(blank=True, null=True)),
                ('finding', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_finding', to='preport.db_finding')),
            ],
        ),
    ]
