# Generated by Django 4.2 on 2023-06-20 10:36

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0002_db_deliverable_share_date_db_deliverable_share_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_report',
            name='audit_objectives',
            field=martor.models.MartorField(blank=True),
        ),
    ]
