# Generated by Django 5.0.3 on 2024-03-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0003_db_cspn_evaluation_stage_db_product_installation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_report',
            name='cvss_version',
            field=models.CharField(blank=True, default='3.1', max_length=200),
        ),
    ]
