# Generated by Django 3.2.15 on 2022-12-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0003_auto_20220919_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_AttackFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('attackflow_afb', models.TextField(blank=True, null=True)),
                ('attackflow_png', models.TextField(blank=True, null=True)),
                ('finding', models.ManyToManyField(blank=True, related_name='attackflow_finding', to='preport.DB_Finding')),
            ],
        ),
    ]
