# Generated by Django 4.2.2 on 2023-06-30 18:30

from django.db import migrations, models
import django.db.models.deletion
import martor.models
import preport.models


class Migration(migrations.Migration):

    # Custom data

    def customer_data(self, schema_editor):
        DBCustomer = self.get_model("preport", "DB_Customer")

        customer = DBCustomer(
                name = "Customer",
                contact = "admin@customer",
                description = "Customer",
            )

        customer.save()

    def owasp_data(self, schema_editor):
        DBOWASP = self.get_model("preport", "DB_OWASP")

        owasp = DBOWASP(
                owasp_id = 0,
                owasp_year = "2021",
                owasp_name = "Not categorized",
                owasp_description = "Not categorized",
                owasp_url = "",
                owasp_full_id = "0",

            )

        owasp.save()


    def settings_data(self, schema_editor):
        DBSettings = self.get_model("preport", "DB_Settings")

        settings = DBSettings(
                company_name = "PeTeReport Tool",
                company_website = "https://github.com/1modm/petereport",
                company_address = "Spain",
                company_picture = "images/company_picture.png",
                report_subject = "Pentest Report",
            )

        settings.save()

    # Custom data


    dependencies = [
        ('preport', '0004_db_attackflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact', models.EmailField(blank=True, max_length=255)),
                ('description', martor.models.MartorField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='DB_OWASP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owasp_id', models.IntegerField(unique=True)),
                ('owasp_year', models.IntegerField()),
                ('owasp_name', models.CharField(blank=True, max_length=255)),
                ('owasp_description', models.TextField(blank=True)),
                ('owasp_url', models.CharField(blank=True, max_length=255)),
                ('owasp_full_id', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'OWASPs',
            },
        ),

        migrations.RunPython(customer_data, owasp_data, atomic=True),

        
        migrations.CreateModel(
            name='DB_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.CharField(blank=True, max_length=255)),
                ('company_address', models.CharField(blank=True, max_length=255)),
                ('report_subject', models.CharField(blank=True, max_length=255)),
                ('company_picture', models.ImageField(blank=True, upload_to=preport.models.logo_dst)),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),

        migrations.RunPython(settings_data, atomic=True),

        migrations.CreateModel(
            name='DB_Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=2048)),
                ('generation_date', models.DateTimeField()),
                ('filetype', models.CharField(max_length=32)),
                ('filetemplate', models.CharField(max_length=64)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preport.db_report')),
            ],
            options={
                'verbose_name_plural': 'Deliverables',
            },
        ),
        migrations.AlterModelOptions(
            name='db_cwe',
            options={'verbose_name_plural': 'CWEs'},
        ),
        migrations.AlterModelOptions(
            name='db_finding',
            options={'verbose_name_plural': 'Findings'},
        ),
        migrations.AlterModelOptions(
            name='db_product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='db_report',
            options={'verbose_name_plural': 'Reports'},
        ),
        migrations.RemoveField(
            model_name='db_report',
            name='categories_summary_image',
        ),
        migrations.AddField(
            model_name='db_finding',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_finding',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='db_finding',
            name='poc',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AddField(
            model_name='db_finding_template',
            name='poc',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AddField(
            model_name='db_report',
            name='audit_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_report',
            name='audit_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='db_report',
            name='cwe_categories_summary_image',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='db_report',
            name='owasp_categories_summary_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='db_finding',
            name='cwe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preport.db_cwe'),
        ),
        migrations.AlterField(
            model_name='db_finding_template',
            name='cwe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preport.db_cwe'),
        ),
        migrations.AlterField(
            model_name='db_product',
            name='description',
            field=martor.models.MartorField(blank=True),
        ),
        migrations.AddField(
            model_name='db_finding',
            name='owasp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preport.db_owasp'),
        ),
        migrations.AddField(
            model_name='db_finding_template',
            name='owasp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preport.db_owasp'),
        ),
        migrations.AddField(
            model_name='db_product',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='preport.db_customer'),
        ),

    ]
