# Generated by Django 3.2.16 on 2023-01-04 15:08

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0004_db_attackflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_finding',
            name='closed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 4, 15, 8, 2, 571785, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db_finding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
