# Generated by Django 5.0.3 on 2024-03-28 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0004_db_report_cvss_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_finding',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DB_Datatables_State_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatables_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=30)),
                ('datatables_state', models.TextField(blank=True)),
                ('datatables_order', models.TextField(blank=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preport.db_report')),
            ],
            options={
                'verbose_name_plural': 'Datatables_State_Order',
            },
        ),
    ]
