# Generated by Django 5.0.3 on 2024-03-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0004_db_report_cvss_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_finding',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
