# Generated by Django 4.2.5 on 2023-12-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0005_db_customer_db_owasp_db_settings_db_shareconnection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_finding',
            old_name='cvss_base_score',
            new_name='cvss_vector',
        ),
        migrations.RenameField(
            model_name='db_finding_template',
            old_name='cvss_base_score',
            new_name='cvss_vector',
        ),
    ]
