# Generated by Django 3.2.16 on 2023-01-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0007_auto_20230105_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_customer',
            name='contact_dp_mail',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='db_customer',
            name='contact_list',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='db_customer',
            name='contact_sp_mail',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
