# Generated by Django 3.2.16 on 2023-01-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0008_auto_20230105_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='db_customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='db_cwe',
            options={'verbose_name_plural': 'CWEs'},
        ),
        migrations.AlterModelOptions(
            name='db_finding',
            options={'verbose_name_plural': 'Findings'},
        ),
        migrations.AlterModelOptions(
            name='db_product',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='db_report',
            options={'verbose_name_plural': 'Reports'},
        ),
        migrations.RemoveField(
            model_name='db_product',
            name='customer',
        ),
        migrations.AddField(
            model_name='db_customer',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='preport.db_product'),
            preserve_default=False,
        ),
    ]
