# Generated by Django 3.2.16 on 2023-01-06 09:10

from django.db import migrations, models
import django.db.models.deletion
import multi_email_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0009_auto_20230105_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_website', models.CharField(max_length=255)),
                ('company_address', models.CharField(max_length=255)),
                ('company_picture', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.AlterField(
            model_name='db_customer',
            name='contact_list',
            field=multi_email_field.fields.MultiEmailField(default=[]),
        ),
        migrations.AlterField(
            model_name='db_customer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preport.db_product'),
        ),
    ]
