# Generated by Django 3.2.16 on 2023-01-08 16:56

from django.db import migrations, models
import preport.models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0010_auto_20230106_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_report',
            name='product',
        ),
        migrations.AddField(
            model_name='db_report',
            name='product',
            field=models.ManyToManyField(to='preport.DB_Product'),
        ),
        migrations.AlterField(
            model_name='db_settings',
            name='company_picture',
            field=models.ImageField(upload_to=preport.models.logo_dst),
        ),
    ]
