# Generated by Django 3.2.16 on 2023-01-08 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0011_auto_20230108_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_customer',
            name='product',
        ),
        migrations.AddField(
            model_name='db_customer',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='preport.DB_Product'),
        ),
        migrations.RemoveField(
            model_name='db_report',
            name='product',
        ),
        migrations.AddField(
            model_name='db_report',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='preport.db_product'),
            preserve_default=False,
        ),
    ]
