# Generated by Django 3.2.16 on 2023-01-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0012_auto_20230108_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_customer',
            name='product',
        ),
        migrations.AddField(
            model_name='db_customer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preport.db_product'),
        ),
    ]
