# Generated by Django 4.1.5 on 2023-01-20 14:16

from django.db import migrations, models
import preport.models


class Migration(migrations.Migration):

    dependencies = [
        ('preport', '0014_auto_20230109_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_settings',
            name='company_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='db_settings',
            name='company_picture',
            field=models.ImageField(blank=True, upload_to=preport.models.logo_dst),
        ),
        migrations.AlterField(
            model_name='db_settings',
            name='company_website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
